[Distribution]
Distribution=arch
Architecture=arm64

[Build]
Incremental=true

[Output]
Format=tar
Output=arch
CompressOutput=zstd

[Content]
ExtraTrees=mkosi.sandbox
Packages=base,mkinitcpio,vulkan-panfrost,wireless-regdb,openssh,networkmanager,kitty,papirus-icon-theme,pipewire-jack,noto-fonts,noto-fonts-emoji,ttf-font-awesome,vim,util-linux,sudo,thunar,greetd,xournalpp
VolatilePackages=brcm-firmware-pinenote,pinenote-arch,koreader-bin,pinenote-hrdl-sway-meta,pneink-theme-git
VolatilePackageDirectories=mkosi.volatilepackages
WithDocs=false
SourceDateEpoch=1745400000
Bootable=false
Bootloader=none
Timezone=Etc/UTC
Hostname=pinenote
RootPassword=rootpass
