[Distribution]
Distribution=arch

[Build]
Incremental=true

[Output]
Format=tar
Output=arch
CompressOutput=zstd

[Content]
Packages=base,mkinitcpio,vulkan-panfrost,wireless-regdb,brcm-firmware-pinenote,openssh,networkmanager,kitty,pinenote-arch,papirus-icon-theme,xournalpp-git,koreader-bin,pipewire-jack,noto-fonts,noto-fonts-emoji,ttf-font-awesome,vim,util-linux,pinenote-hrdl-sway-meta,archlinuxarm-keyring,sudo,thunar,pneink-theme-git
WithDocs=false
SourceDateEpoch=1745400000
Bootable=false
Bootloader=none
Timezone=Etc/UTC
Hostname=pinenote
RootPassword=rootpass
