timeout 10
default linux-pinenote-hrdl
menu title boot prev kernel

label linux-pinenote-hrdl
  kernel /boot/Image
  fdt /boot/rk3566-pinenote-v1.2.dtb
  initrd /boot/initramfs-linux.img
  append root=/dev/mmcblk0p6 rw rootwait earlycon console=tty0 console=ttyS2,1500000n8 fw_devlink=off
